language: node_js
node_js:
- '0.10'
services:
  - redis-server
cache:
  directories:
    - $GEM_HOME
    - node_modules	
branches:
  only:
    - master
    - dev
install:
  - rvm 1.9.3 do gem install dpl
  - npm -g install npm@latest
before_install:
  - npm install -g grunt-cli
  - npm install -g bower@1.4.1
  - npm install -g azure-cli
  - npm install
  - node travis_ini.js
before_script:
  - chmod -R 777 ./travis_notify.sh
  - chmod -R 777 ./travis_grunt.sh
  - chmod -R 777 ./travis_azure.sh
  - chmod -R 777 ./app
  - bower install
  - ./travis_grunt.sh
  - ./app stop  
after_success:
  - sudo rm -rf ./node_modules/*
  - sudo rm -rf ./.git/*
  - sudo rm -rf ./node_modules/.bin
  - rm *.log
  - sudo rm -rf ./bower_components/backbone/* 
  - sudo rm -rf ./bower_components/jquery/* 
  - ./travis_azure.sh
  - ./travis_notify.sh 
